#include QMK_KEYBOARD_H

const uint16_t PROGMEM keymaps[][MATRIX_ROWS][MATRIX_COLS] = {
	[0] = LAYOUT_split_3x6_3(
            LT(6, KC_ESC), KC_Q, KC_W, KC_E, KC_R, KC_T,                                        /****/   KC_Y, KC_U, KC_I, KC_O, KC_P, LT(9, KC_MPLY),
            MO(7), LSFT_T(KC_A), LCTL_T(KC_S), LALT_T(KC_D), LGUI_T(KC_F), ALL_T(KC_G),         /****/   ALL_T(KC_H), RGUI_T(KC_J), RALT_T(KC_K), RCTL_T(KC_L), RSFT_T(KC_SCLN), LT(7, KC_QUOT),
            LT(8, KC_MUTE), KC_Z, KC_X, KC_C, KC_V, KC_B,                                       /****/   KC_N, KC_M, KC_COMM, KC_DOT, KC_SLSH, LT(8, KC_MUTE), LT(1, KC_ESC),
            LT(2, KC_SPC), LT(3, KC_TAB), LT(3, KC_ENT),                                        /****/   LT(4, KC_BSPC), LT(5, KC_DEL)
        ),
	[1] = LAYOUT_split_3x6_3(_______, XXXXXXX, XXXXXXX, XXXXXXX, XXXXXXX, XXXXXXX, XXXXXXX, KC_BRID, KC_BRIU, XXXXXXX, XXXXXXX, _______, _______, KC_LSFT, KC_LCTL, KC_LOPT, KC_LGUI, KC_HYPR, KC_MUTE, KC_VOLD, KC_VOLU, KC_MUTE, XXXXXXX, XXXXXXX, _______, XXXXXXX, XXXXXXX, XXXXXXX, XXXXXXX, XXXXXXX, XXXXXXX, KC_MPRV, KC_MNXT, XXXXXXX, XXXXXXX, _______, _______, _______, _______, HYPR(KC_3), HYPR(KC_4), HYPR(KC_5)),
	[2] = LAYOUT_split_3x6_3(_______, LGUI(KC_Q), LGUI(KC_W), LGUI(KC_F), LGUI(KC_R), LGUI(KC_T), KC_PGUP, KC_HOME, KC_UP, KC_END, XXXXXXX,  _______, _______, KC_LSFT, LGUI(KC_S), KC_LOPT, KC_LGUI, KC_HYPR, KC_PGDN, KC_LEFT, KC_DOWN, KC_RGHT, XXXXXXX, XXXXXXX, _______, LGUI(KC_Z), LGUI(KC_X), LGUI(KC_C), LGUI(KC_V), LGUI(KC_B), XXXXXXX, XXXXXXX, XXXXXXX, XXXXXXX, XXXXXXX, _______, _______, _______, _______, _______, _______, _______),
	[3] = LAYOUT_split_3x6_3(_______, KC_CIRC, KC_PIPE, KC_LBRC, KC_RBRC, KC_SLSH, KC_HASH, KC_LT, KC_GT, KC_TILD, XXXXXXX, _______, _______, KC_AT, KC_EQL, KC_LCBR, KC_RCBR, KC_ASTR, KC_UNDS, KC_LPRN, KC_RPRN, KC_COLN, KC_SCLN, XXXXXXX, _______, KC_PERC, KC_AMPR, KC_QUOT, KC_DQUO, KC_MINS, KC_GRV, KC_DLR, KC_BSLS, KC_SLSH, XXXXXXX, _______, KC_EXLM, KC_QUES, KC_MINS, KC_PLUS, KC_DOT, KC_COMM),
	[4] = LAYOUT_split_3x6_3(_______, KC_CIRC, KC_P7, KC_P8, KC_P9, KC_PSLS, XXXXXXX, XXXXXXX, XXXXXXX, XXXXXXX, XXXXXXX, _______, _______, MY_EURO, KC_P4, KC_P5, KC_P6, KC_PAST, XXXXXXX, XXXXXXX, XXXXXXX, XXXXXXX, XXXXXXX, XXXXXXX, _______, KC_PERC, KC_P1, KC_P2, KC_P3, KC_PMNS, XXXXXXX, XXXXXXX, XXXXXXX, XXXXXXX, XXXXXXX, _______, KC_PDOT, KC_P0, KC_PPLS, _______, _______, _______),
	[5] = LAYOUT_split_3x6_3(_______, MY_LOCK, XXXXXXX, HYPR(KC_UP), XXXXXXX, SGUI(KC_3), XXXXXXX, XXXXXXX, XXXXXXX, XXXXXXX, XXXXXXX, _______, _______, XXXXXXX, HYPR(KC_LEFT), HYPR(KC_DOWN), HYPR(KC_RGHT), SGUI(KC_4), KC_HYPR, KC_RGUI, KC_ROPT, KC_RCTL, KC_RSFT, XXXXXXX, _______, XXXXXXX, XXXXXXX, XXXXXXX, XXXXXXX, SGUI(KC_5), XXXXXXX, XXXXXXX, XXXXXXX, XXXXXXX, XXXXXXX, _______, HYPR(KC_1), LGUI(KC_SPC), HYPR(KC_2), _______, _______, _______),
	[6] = LAYOUT_split_3x6_3(_______, RGB_VAD, RGB_VAI, RGB_RMOD, RGB_MOD, XXXXXXX, XXXXXXX, XXXXXXX, XXXXXXX, XXXXXXX, XXXXXXX, _______, _______, RGB_TOG, RGB_TOG, RGB_SPD, RGB_SPI, XXXXXXX, XXXXXXX, XXXXXXX, XXXXXXX, XXXXXXX, XXXXXXX, XXXXXXX, _______, RGB_SAD, RGB_SAI, RGB_HUD, RGB_HUI, XXXXXXX, XXXXXXX, XXXXXXX, XXXXXXX, XXXXXXX, XXXXXXX, _______, _______, _______, _______, _______, _______, _______),
	[7] = LAYOUT_split_3x6_3(_______, _______, _______, _______, _______, _______, _______, _______, _______, _______, _______, _______, _______, KC_A, KC_S, KC_D, KC_F, KC_G, KC_H, KC_J, KC_K, KC_L, KC_SCLN, XXXXXXX, _______, _______, _______, _______, _______, _______, _______, _______, _______, _______, _______, _______, _______, _______, _______, _______, _______, _______),
	[8] = LAYOUT_split_3x6_3(_______, XXXXXXX, XXXXXXX, DM_REC1, DM_REC2, XXXXXXX, XXXXXXX, DM_REC2, DM_REC1, XXXXXXX, XXXXXXX, _______, _______, XXXXXXX, XXXXXXX, DM_PLY1, DM_PLY2, XXXXXXX, XXXXXXX, DM_PLY2, DM_PLY1, XXXXXXX, XXXXXXX, XXXXXXX, _______, XXXXXXX, XXXXXXX, XXXXXXX, XXXXXXX, XXXXXXX, XXXXXXX, XXXXXXX, XXXXXXX, XXXXXXX, XXXXXXX, _______, _______, _______, _______, _______, _______, _______),
	[9] = LAYOUT_split_3x6_3(_______, _______, _______, _______, _______, _______, _______, _______, _______, KC_VOLU, KC_MNXT, _______, _______, _______, _______, _______, _______, _______, _______, _______, _______, KC_VOLD, KC_MPRV, XXXXXXX, _______, _______, _______, _______, _______, _______, _______, _______, _______, KC_MUTE, KC_MUTE, _______, _______, _______, _______, _______, _______, _______)
};
